/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Circle006: THREE.Mesh;
    Circle006_1: THREE.Mesh;
  };
  materials: {
    MI_MZRa_Monstera_B02a: THREE.MeshStandardMaterial;
    MI_MZRa_Monstera_B02b: THREE.MeshStandardMaterial;
  };
};

export function Plant(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/plant.glb") as GLTFResult;
  return (
    <group {...props} dispose={null} scale={70} rotation={[.5*Math.PI,0,0]} position={[0,0,15]}>
      <mesh
        geometry={nodes.Circle006.geometry}
        material={materials.MI_MZRa_Monstera_B02a}
      />
      <mesh
        geometry={nodes.Circle006_1.geometry}
        material={materials.MI_MZRa_Monstera_B02b}
      />
    </group>
  );
}

useGLTF.preload("/models/plant.glb");