name: deploy

on:
  push:
    branches:
      - main         # production用
      - develop  # develop用

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Node 12 for /core
      uses: actions/setup-node@v3
      with: 
        node-version: '12.20.1'
        registry-url: 'https://registry.npmjs.org'
    - name: Install wasm-pack
      run: |
            curl -sSf https://rustwasm.github.io/wasm-pack/installer/init.sh | sh
    - name: Install Dependencies @nodi/core
      working-directory: ./core
      run: |
        yarn install
      # 事前にwasm-packをインストール
      
    - name: Build @nodi/core
      working-directory: ./core
      run: |
        yarn build
    
    - name: Set up Node.js 18 for /web
      uses: actions/setup-node@v3
      with:
        node-version: '18.18.0'
        registry-url: 'https://registry.npmjs.org'
    - name: Install Dependencies @nodi/web
      working-directory: ./web
      run: |
        yarn remove @nodi/core
        yarn add ../core
        npm install -g firebase-tools
        yarn install
    - name: Verify Firebase Authentication  # ← ここに追加！
      working-directory: ./web
      run: |
          firebase login:ci
    - name: Create .firebase.env.js file
      working-directory: ./web
      env:
        FIREBASE_ENV_FILE: ${{ secrets.FIREBASE_ENV_FILE }}
      run: |
        echo $FIREBASE_ENV_FILE | base64 --decode > .firebase.env.js
    - name: Create .firebaserc file
      working-directory: ./web
      env:
        FIREBASE_RC_FILE: ${{ secrets.FIREBASE_RC_FILE }}
      run: |
        echo $FIREBASE_RC_FILE | base64 --decode > .firebaserc
    - name: Generate @nodi/web
      working-directory: ./web
      run: yarn generate
#    - name: Test
#      working-directory: ./web
#      run: yarn test
    - name: Deploy to Firebase
      working-directory: ./web
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          firebase use production
          yarn firebase:deploy --only hosting:production
        elif [[ "${{ github.ref_name }}" == "develop" ]]; then
          firebase use stagung
          yarn firebase:deploy --only hosting:staging
        fi